# HA Control Plane

[kube_control_plane]
master1 ansible_host=172.31.35.181 ip=172.31.35.181 etcd_member_name=etcd1
master2 ansible_host=172.31.36.212 ip=172.31.36.212 etcd_member_name=etcd2
master3 ansible_host=172.31.35.11  ip=172.31.35.11  etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
